name: Push Action
on:
  push:
    paths:
      - 'sound/**'
      - 'lua/chatsounds/lists_nosend/**'
jobs:
  check:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Preprocessor 🔧
        uses: Metastruct/chatsounds-preprocessor-action@v1
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Preprocessor 🔧
        uses: Metastruct/chatsounds-preprocessor-action@v1

      - name: Deploy 🚀
        uses: EndBug/add-and-commit@v7
        with:
          add: 'lua/chatsounds/lists_nosend'
          author_name: Meta Automator
          author_email: MetaAutomator@users.noreply.github.com
          default_author: user_info
          pull: 'NO-PULL'
